version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}notesweb
    build:
      context: .
      dockerfile: src/Notes.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - SqlServer__ConnectionString=Server=sqlserver,1433;Database=Application;User=sa;Password=P@ssw0rd;TrustServerCertificate=true;
      - Initialization__InitializeOnStartup=true
    ports:
      - 5000:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433
    volumes:
      - sqlserver:/var/opt/mssql
volumes:
  sqlserver: