@baseurl=https://localhost:5000/api/v1

POST {{baseurl}}/notes
Content-Type: application/json

{
  "title": "Title",
  "content": "Content"
}

###

POST {{baseurl}}/notes/batch-generate
Content-Type: application/json

{
  "amount": 1000
}

###

GET {{baseurl}}/notes