version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}notesweb
    build:
      context: .
      dockerfile: src/Notes.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - Mongo__Connection=mongodb://mongo:27017
      - Mongo__Database=Application
    ports:
      - 5000:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - mongo
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017